name: Deploy Static Content to GitHub Pages

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one deployment happens at a time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build Static Content
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Verify directory exists
        run: |
          if [ ! -d "./docs" ]; then
            echo "::error::The docs directory does not exist!"
            exit 1
          fi
          if [ -z "$(ls -A ./docs)" ]; then
            echo "::error::The docs directory is empty!"
            exit 1
          fi
          echo "✅ Docs directory exists and contains files"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Calculate checksum of docs
        run: find ./docs -type f -exec sha256sum {} \; | sort > docs_checksum.txt
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
      - name: Upload checksum for verification
        uses: actions/upload-artifact@v3
        with:
          name: docs-checksum
          path: docs_checksum.txt
          
  verify:
    name: Verify Build Integrity
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download checksum
        uses: actions/download-artifact@v3
        with:
          name: docs-checksum
          
      - name: Download GitHub Pages artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          
      - name: Extract artifact
        run: tar -xf artifact.tar
        
      - name: Verify checksum
        run: |
          find . -type f -not -path "./docs_checksum.txt" -not -path "./artifact.tar" -exec sha256sum {} \; | sort > current_checksum.txt
          if cmp -s docs_checksum.txt current_checksum.txt; then
            echo "✅ Checksums match - build integrity verified"
          else
            echo "::error::Checksums do not match!"
            echo "Expected:"
            cat docs_checksum.txt
            echo "Actual:"
            cat current_checksum.txt
            exit 1
          fi
          
  deploy:
    name: Deploy to GitHub Pages
    needs: verify
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4